/*
 * Copyright (c) 2022-2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import UIAbility from '@ohos.app.ability.UIAbility';
import AbilityDelegatorRegistry from '@ohos.app.ability.abilityDelegatorRegistry';
import { Hypium } from '@ohos/hypium';
import testsuite from "../test/List.test";
import Want from '@ohos.app.ability.Want';
import AbilityConstant from '@ohos.app.ability.AbilityConstant';
import hilog from '@ohos.hilog';
import window from '@ohos.window';

export default class TestAbility extends UIAbility {
  onCreate( want : Want , launchParam : AbilityConstant.LaunchParam ) {
    hilog.info( 0x0000 , 'testTag' , 'TestAbility onCreate' );
  }

  onDestroy() {
    hilog.info( 0x0000 , 'testTag' , 'TestAbility onDestroy' );
  }

  onWindowStageCreate( windowStage : window.WindowStage ) {
    hilog.info( 0x0000 , 'testTag' , 'TestAbility onWindowStageCreate' );
    windowStage.loadContent( 'testability/pages/Index' , ( err , data ) => {
      if( err.code ) {
        hilog.info( 0x0000 , 'testTag' , 'Failed to load the content. Cause:' + JSON.stringify( err ) );
        return;
      }
      hilog.info( 0x0000 , 'testTag' , 'Succeeded in loading the content. Data: ' + JSON.stringify( data ) );
    } );
    let abilityDelegator : AbilityDelegatorRegistry.AbilityDelegator;
    abilityDelegator = AbilityDelegatorRegistry.getAbilityDelegator();
    let abilityDelegatorArguments : AbilityDelegatorRegistry.AbilityDelegatorArgs;
    abilityDelegatorArguments = AbilityDelegatorRegistry.getArguments();
    hilog.info( 0x0000 , 'testTag' , 'start run testcase!!!' );
    Hypium.hypiumTest( abilityDelegator , abilityDelegatorArguments , testsuite );
  }

  onWindowStageDestroy() {
    hilog.info( 0x0000 , 'testTag' , 'TestAbility onWindowStageDestroy' );
  }

  onForeground() {
    hilog.info( 0x0000 , 'testTag' , 'TestAbility onForeground' );
  }

  onBackground() {
    hilog.info( 0x0000 , 'testTag' , 'TestAbility onBackground' );
  }
}