/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the 'License');
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an 'AS IS' BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { es2abcErrorReferences } from './url_config.json';

export enum SubsystemCode {
  ETS2BUNDLE = '103',
  ABC2PROGRAM = '104',
  ES2ABC = '107',
}

export enum ErrorCode {
  // INTERNAL ERRORS
  ETS2BUNDLE_INTERNAL_UNABLE_TO_RETRIEVE_SOURCE_CODE_FROM_SUMMARY = '10310001',
  ETS2BUNDLE_INTERNAL_UNABLE_TO_GENERATE_CACHE_SOURCE_FILE = '10310002',
  ETS2BUNDLE_INTERNAL_UNABLE_TO_RETRIEVE_PACKAGE_CACHE_IN_INCREMENTAL_BUILD = '10310003',
  ETS2BUNDLE_INTERNAL_INVALID_COMPILE_MODE = '10310004',
  ETS2BUNDLE_INTERNAL_HASH_JSON_FILE_GENERATION_MISSING_PATHS = '10310005',
  ETS2BUNDLE_INTERNAL_INCREMENTAL_BUILD_MISSING_CACHE_ABC_FILE_PATH = '10310006',
  ETS2BUNDLE_INTERNAL_COLD_RELOAD_FAILED_INCORRECT_SYMBOL_MAP_CONFIG = '10310007',
  ETS2BUNDLE_INTERNAL_HOT_RELOAD_FAILED_INCORRECT_SYMBOL_MAP_CONFIG = '10310008',
  ETS2BUNDLE_INTERNAL_MODULE_INFO_NOT_FOUND = '10310009',
  ETS2BUNDLE_INTERNAL_META_INFO_NOT_FOUND = '10310010',
  ETS2BUNDLE_INTERNAL_MOCK_CONFIG_KEY_TO_OHM_URL_CONVERSION_FAILED = '10310011',
  ETS2BUNDLE_INTERNAL_GET_MODULE_INFO_FAILED = '10310012',
  ETS2BUNDLE_INTERNAL_UNABLE_TO_GET_MODULE_INFO_META = '10310013',
  ETS2BUNDLE_INTERNAL_UNABLE_TO_GET_MODULE_INFO_META_PKG_PATH = '10310014',
  ETS2BUNDLE_INTERNAL_WRITE_SOURCE_MAP_FAILED = '10310015',
  ETS2BUNDLE_INTERNAL_UNABLE_TO_GET_PKG_CONTENT_INFO = '10310016',
  ETS2BUNDLE_INTERNAL_PACKAGE_NOT_FOUND_IN_CONTEXT_INFO = '10310017',
  ETS2BUNDLE_INTERNAL_PACKAGE_ENTRY_FILE_NOT_FOUND = '10310018',
  ETS2BUNDLE_INTERNAL_ARKGUARD_OBFUSCATION_FAILED = '10310019',
  ETS2BUNDLE_INTERNAL_SOURCE_CODE_OBFUSCATION_FAILED = '10310020',
  ETS2BUNDLE_INTERNAL_ES2ABC_SUBPROCESS_START_FAILED = '10310021',
  ETS2BUNDLE_INTERNAL_EXECUTE_ES2ABC_WITH_ASYNC_HANDLER_FAILED = '10310022',

  // EXTERNAL ERRORS
  ETS2BUNDLE_EXTERNAL_FORBIDDEN_IMPORT_ARKTS_FILE = '10311001',
  ETS2BUNDLE_EXTERNAL_FAILED_TO_RESOLVE_OHM_URL = '10311002',
  ETS2BUNDLE_EXTERNAL_KIT_CONFIG_FILE_NOT_FOUND = '10311003',
  ETS2BUNDLE_EXTERNAL_LAZY_IMPORT_NOT_ALLOWED_WITH_KIT = '10311004', // Deprecated
  ETS2BUNDLE_EXTERNAL_IDENTIFIER_IMPORT_NOT_ALLOWED_IN_TS_FILE = '10311005',
  ETS2BUNDLE_EXTERNAL_IMPORT_NAME_NOT_EXPORTED_FROM_KIT = '10311006',
  ETS2BUNDLE_EXTERNAL_KIT_NAMESPACE_IMPORT_EXPORT_NOT_SUPPORTED = '10311007',
  ETS2BUNDLE_EXTERNAL_EMPTY_IMPORT_NOT_ALLOWED_WITH_KIT = '10311008',
  ETS2BUNDLE_EXTERNAL_ES2ABC_EXECUTION_FAILED = '10311009',
  ETS2BUNDLE_EXTERNAL_LAZY_IMPORT_RE_EXPORT_ERROR = '10311010',
  ETS2BUNDLE_EXTERNAL_DUPLICATE_FILE_NAMES_ERROR = '10311011',

  // CONSTANTS FOR ES2ABC ERROR CODE
  ES2ABC_SYNTAX_ERROR_ERROR_CODE = '10705000',
  ES2ABC_PATCH_FIX_ERROR_ERROR_CODE = '10706001',

  //BYTECODE OBFUSCATION ERROR CODE
  BYTECODE_OBFUSCATION_UNSUPPORT_COMPATIBLESDKVERSION = '11306001',
  BYTECODE_OBFUSCATION_COMMON_ERROR = '11310001',
  ETS2BUNDLE_INTERNAL_ESBYTECODE_OBFUSCATIONABC_SUBPROCESS_START_FAILED = '11310002'
}

// DESCRIPTION
export const ArkTSInternalErrorDescription: string = 'ArkTS: INTERNAL ERROR';
export const ArkTSErrorDescription: string = 'ArkTS: ERROR';

// CONSTANTS FOR ES2ABC ERROR CODE
// ES2ABC_SYNTAX_ERROR_ERROR_CODE 10705000
export const ES2ABC_SYNTAX_ERROR_PREFIX = 'SyntaxError: ';
export const ES2ABC_SYNTAX_ERROR_DESCRIPTION = 'Syntax Error';
// ES2ABC_PATCH_FIX_ERROR_ERROR_CODE 10706001
export const ES2ABC_PATCH_FIX_ERROR_PREFIX = '[Patch] ';
export const ES2ABC_PATCH_FIX_ERROR_DESCRIPTION = 'Unsupported Change in Hot Reload';
export const ES2ABC_PATCH_FIX_ERROR_ACTION = 'For more details on hot reload specification, ' +
  `please refer to ${es2abcErrorReferences.harmonyOSGuideHotReload}.`;

export const ES2ABC_ERROR_MAPPING: Record<string, { code: string; description: string; solutions: string[] }> = {
  [ES2ABC_SYNTAX_ERROR_PREFIX]: {
    code: ErrorCode.ES2ABC_SYNTAX_ERROR_ERROR_CODE,
    description: ES2ABC_SYNTAX_ERROR_DESCRIPTION,
    solutions: [],
  },
  [ES2ABC_PATCH_FIX_ERROR_PREFIX]: {
    code: ErrorCode.ES2ABC_PATCH_FIX_ERROR_ERROR_CODE,
    description: ES2ABC_PATCH_FIX_ERROR_DESCRIPTION,
    solutions: [ES2ABC_PATCH_FIX_ERROR_ACTION],
  },
};