/**
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export { ContactRepository } from './src/main/ets/repo/ContactRepository'

export { DataItem } from './src/main/ets/entity/DataItem'

export { Data } from './src/main/ets/contract/Data'
export { DataItemType } from './src/main/ets/contract/DataType'
export { RawContacts } from './src/main/ets/contract/RawContacts'
export { Contacts } from './src/main/ets/contract/Contacts'

export { Phone } from './src/main/ets/contract/Phone'
export { Email } from './src/main/ets/contract/Email'
export { House } from './src/main/ets/contract/House'
export { Birthday } from './src/main/ets/contract/Birthday'
export { Aim } from './src/main/ets/contract/Aim'
export { Im } from './src/main/ets/contract/Im'
export { StructuredPostal } from './src/main/ets/contract/StructuredPostal'
export { Event } from './src/main/ets/contract/Event'
export { Relation } from './src/main/ets/contract/Relation'
