/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @file iimage_process_callback.h
 *
 * @brief Declares callbacks for image process.
 *
 * @since 4.1
 * @version 1.2
 */

package ohos.hdi.camera.v1_2;
import ohos.hdi.camera.v1_2.Types;

[callback] interface IImageProcessCallback {
    /**
     * @brief Called when the process done.
     * For details about the reporting mode, see {@link SetResultMode}.
     *
     * @param imageId Indicates the image ID.
     * @param buffer Indicates buffer.
     *
     * @since 4.1
     * @version 1.2
     */
    OnProcessDone([in] String imageId, [in] ImageBufferInfo buffer);

    /**
     * @brief Called when the process status changed.
     * For details about the reporting mode, see {@link SetResultMode}.
     *
     * @param status Indicates the new status of the Session.
     *
     * @since 4.1
     * @version 1.2
     */
    OnStatusChanged([in] enum SessionStatus status);

    /**
     * @brief Called when an error occurs when processing the session.
     *
     * @since 4.1
     * @version 1.2
     */
    OnError([in] String imageId, [in] enum ErrorCode errorCode);
}