/**
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http:www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import router_getStateByUrl1 from './router/router_getStateByUrl1.test'
import router_getStateByUrl2 from './router/router_getStateByUrl2.test'
import router_getStateByIndex3 from './router/router_getStateByIndex3.test'
import router_getStateByIndex4 from './router/router_getStateByIndex4.test'
import router_getStateByUrl5 from './router/router_getStateByUrl5.test'
import router_back6 from './router/router_back6.test'
import router_back7 from './router/router_back7.test'
import router_back8 from './router/router_back8.test'
import router_back9 from './router/router_back9.test'
import router_back10 from './router/router_back10.test'
import router_back11 from './router/router_back11.test'
import router_back12 from './router/router_back12.test'
import router_back13 from './router/router_back13.test'
import router_getStateByUrl14 from './router/router_getStateByUrl14.test'
import router_back15 from './router/router_back15.test'
import router_getStateByIndex16 from './router/router_getStateByIndex16.test'

import replaceUrl2 from './router/replaceUrl/replaceUrl2.test'
import replaceUrl3 from './router/replaceUrl/replaceUrl3.test'
import replaceUrl5 from './router/replaceUrl/replaceUrl5.test'
import replaceUrl6 from './router/replaceUrl/replaceUrl6.test'
import replaceUrl8 from './router/replaceUrl/replaceUrl8.test'
import replaceUrl9 from './router/replaceUrl/replaceUrl9.test'
import replaceUrl10 from './router/replaceUrl/replaceUrl10.test'
import replaceUrl12 from './router/replaceUrl/replaceUrl12.test'
import replaceUrl13 from './router/replaceUrl/replaceUrl13.test'
import replaceUrl14 from './router/replaceUrl/replaceUrl14.test'

import replaceNamedRoute2 from './router/replaceNamedRoute/replaceNamedRoute2.test'
import replaceNamedRoute3 from './router/replaceNamedRoute/replaceNamedRoute3.test'
import replaceNamedRoute5 from './router/replaceNamedRoute/replaceNamedRoute5.test'
import replaceNamedRoute6 from './router/replaceNamedRoute/replaceNamedRoute6.test'
import replaceNamedRoute8 from './router/replaceNamedRoute/replaceNamedRoute8.test'
import replaceNamedRoute9 from './router/replaceNamedRoute/replaceNamedRoute9.test'
import replaceNamedRoute10 from './router/replaceNamedRoute/replaceNamedRoute10.test'
import replaceNamedRoute12 from './router/replaceNamedRoute/replaceNamedRoute12.test'
import replaceNamedRoute13 from './router/replaceNamedRoute/replaceNamedRoute13.test'
import replaceNamedRoute14 from './router/replaceNamedRoute/replaceNamedRoute14.test'

import back1 from './router/back/back1.test'
import back2 from './router/back/back2.test'
import back3 from './router/back/back3.test'
import back4 from './router/back/back4.test'
import back5 from './router/back/back5.test'
import back6 from './router/back/back6.test'
import back7 from './router/back/back7.test'
import back8 from './router/back/back8.test'
import back9 from './router/back/back9.test'
import back10 from './router/back/back10.test'
import back11 from './router/back/back11.test'

import clear1 from './router/clear/clear1.test'
import getLength1 from './router/getLength/getLength1.test'
import getLength2 from './router/getLength/getLength2.test'
import getLength3 from './router/getLength/getLength3.test'
import getState1 from './router/getState/getState1.test'
import getStateByIndex1 from './router/getStateByIndex/getStateByIndex1.test'

import pushUrl2 from './router/pushUrl/pushUrl2.test'
import pushUrl3 from './router/pushUrl/pushUrl3.test'
import pushUrl4 from './router/pushUrl/pushUrl4.test'
import pushUrl6 from './router/pushUrl/pushUrl6.test'
import pushUrl7 from './router/pushUrl/pushUrl7.test'
import pushUrl8 from './router/pushUrl/pushUrl8.test'
import pushUrl10 from './router/pushUrl/pushUrl10.test'
import pushUrl11 from './router/pushUrl/pushUrl11.test'
import pushUrl12 from './router/pushUrl/pushUrl12.test'
import pushUrl14 from './router/pushUrl/pushUrl14.test'
import pushUrl15 from './router/pushUrl/pushUrl15.test'
import pushUrl16 from './router/pushUrl/pushUrl16.test'
import pushUrl18 from './router/pushUrl/pushUrl18.test'
import pushUrl19 from './router/pushUrl/pushUrl19.test'
import pushUrl20 from './router/pushUrl/pushUrl20.test'
import pushUrl22 from './router/pushUrl/pushUrl22.test'
import pushUrl23 from './router/pushUrl/pushUrl23.test'
import pushUrl24 from './router/pushUrl/pushUrl24.test'

import pushNamedRoute2 from './router/pushNamedRoute/pushNamedRoute2.test'
import pushNamedRoute3 from './router/pushNamedRoute/pushNamedRoute3.test'
import pushNamedRoute4 from './router/pushNamedRoute/pushNamedRoute4.test'
import pushNamedRoute6 from './router/pushNamedRoute/pushNamedRoute6.test'
import pushNamedRoute7 from './router/pushNamedRoute/pushNamedRoute7.test'
import pushNamedRoute8 from './router/pushNamedRoute/pushNamedRoute8.test'
import pushNamedRoute10 from './router/pushNamedRoute/pushNamedRoute10.test'
import pushNamedRoute11 from './router/pushNamedRoute/pushNamedRoute11.test'
import pushNamedRoute12 from './router/pushNamedRoute/pushNamedRoute12.test'
import pushNamedRoute14 from './router/pushNamedRoute/pushNamedRoute14.test'
import pushNamedRoute15 from './router/pushNamedRoute/pushNamedRoute15.test'
import pushNamedRoute16 from './router/pushNamedRoute/pushNamedRoute16.test'
import pushNamedRoute18 from './router/pushNamedRoute/pushNamedRoute18.test'
import pushNamedRoute19 from './router/pushNamedRoute/pushNamedRoute19.test'
import pushNamedRoute20 from './router/pushNamedRoute/pushNamedRoute20.test'
import pushNamedRoute22 from './router/pushNamedRoute/pushNamedRoute22.test'
import pushNamedRoute23 from './router/pushNamedRoute/pushNamedRoute23.test'
import pushNamedRoute24 from './router/pushNamedRoute/pushNamedRoute24.test'

export default function testsuite() {
  router_getStateByUrl1();
  router_getStateByUrl2();
  router_getStateByIndex3();
  router_getStateByIndex4();
  router_getStateByUrl5();
  router_back6();
  router_back7();
  router_back8();
  router_back9();
  router_back10();
  router_back11();
  router_back12();
  router_back13();
  router_getStateByUrl14();
  router_back15();
  router_getStateByIndex16();

  replaceUrl2();
  replaceUrl3();
  replaceUrl5();
  replaceUrl6();
  replaceUrl8();
  replaceUrl9();
  replaceUrl10();
  replaceUrl12();
  replaceUrl13();
  replaceUrl14();

  replaceNamedRoute2();
  replaceNamedRoute3();
  replaceNamedRoute5();
  replaceNamedRoute6();
  replaceNamedRoute8();
  replaceNamedRoute9();
  replaceNamedRoute10();
  replaceNamedRoute12();
  replaceNamedRoute13();
  replaceNamedRoute14();

  back1();
  back2();
  back3();
  back4();
  back5();
  back6();
  back7();
  back8();
  back9();
  back10();
  back11();

  clear1();
  getLength1();
  getLength2();
  getLength3();
  getState1();
  getStateByIndex1();

  pushUrl2();
  pushUrl3();
  pushUrl4();
  pushUrl6();
  pushUrl7();
  pushUrl8();
  pushUrl10();
  pushUrl11();
  pushUrl12();
  pushUrl14();
  pushUrl15();
  pushUrl16();
  pushUrl18();
  pushUrl19();
  pushUrl20();
  pushUrl22();
  pushUrl23();
  pushUrl24();

  pushNamedRoute2();
  pushNamedRoute3();
  pushNamedRoute4();
  pushNamedRoute6();
  pushNamedRoute7();
  pushNamedRoute8();
  pushNamedRoute10();
  pushNamedRoute11();
  pushNamedRoute12();
  pushNamedRoute14();
  pushNamedRoute15();
  pushNamedRoute16();
  pushNamedRoute18();
  pushNamedRoute19();
  pushNamedRoute20();
  pushNamedRoute22();
  pushNamedRoute23();
  pushNamedRoute24();
}