/*
 * Copyright (c) 2022-2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

@Entry
@Component
struct AttrAnimationCard {
  @State rotateAngle: number = 0;

  build() {
    Column() {
      Button() {
        Text($r('app.string.change_rotate_angle'))
          .fontColor('#45A6F4')
          .fontSize(12)
      }
      .width(120)
      .height(32)
      .backgroundColor('#FFFFFF')
      .borderRadius(16)
      .onClick(() => {
        this.rotateAngle = (this.rotateAngle === 0 ? 90 : 0);
      })
      .rotate({ angle: this.rotateAngle })
      .animation({
        curve: Curve.EaseOut,
        playMode: PlayMode.Normal,
      })
    }.height('100%').width('100%')
    .justifyContent(FlexAlign.Center)
    .backgroundImage($r('app.media.CardExampleBkg'))
    .backgroundImageSize(ImageSize.Cover)
  }
}