/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class CommonConstants {
  /**
   * Index page Tag.
   */
  public static readonly INDEX_TAG: string = 'INDEX';

  /**
   * PX.
   */
  public static readonly PX: string = 'px';

  /**
   * Default value.
   */
  public static readonly DEFAULT_VALUE: number = 0;

  /**
   * Default width.
   */
  public static readonly DEFAULT_WIDTH: number = 1920;

  /**
   * Default height.
   */
  public static readonly DEFAULT_HEIGHT: number = 1080;

  /**
   * Duration.
   */
  public static readonly DURATION: number = 2000;

  /**
   * The distance between toast dialog box and the bottom of screen.
   */
  public static readonly BOTTOM: number = 80;

  /**
   * Full size.
   */
  public static readonly FULL_SIZE: string = '100%';
}