/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ComponentCard } from '../../common/Card';

@Entry
@Component
export struct TextInputAddEvent {
  @State eventText: ResourceStr = $r('app.string.TextInputAddEvent_textContent_1');
  @State inputValue: ResourceStr = $r('app.string.TextInputAddEvent_textContent_2');

  build() {
    NavDestination() {
      Column({ space: 12 }) {
        ComponentCard({ title: $r('app.string.TextInputAddEvent_title_1') }) {
          Column({ space: 8 }) {
            Text(this.eventText)
            Text(this.inputValue)
            // [Start add_text_input_event]
            TextInput()
              .onChange((value: string) => {
                this.inputValue = value;
              })
              .onFocus(() => {
                this.eventText = $r('app.string.TextInputAddEvent_textContent_3');
              })
            // [End add_text_input_event]
          }
        }
      }
      .width('100%')
      .height('100%')
      .padding({ left: 12, right: 12 })
    }
    .backgroundColor('#f1f2f3')
    .title($r('app.string.TextInputAddEvent_title'))
  }
}